# This file defines the planning limits for MoveIt.
# Values here can override URDF limits if 'has_velocity_limits' is true.

default_velocity_scaling_factor: 0.9
default_acceleration_scaling_factor: 0.9

joint_limits:
  joint_1:
    has_position_limits: true
    min_position: 0.0
    max_position: 6.283185
    has_velocity_limits: true
    max_velocity: 3.1415
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_2:
    has_position_limits: true
    min_position: -1.570796
    max_position: 1.570796
    has_velocity_limits: true
    max_velocity: 1.5708
    has_acceleration_limits: true
    max_acceleration: 2.5
  joint_3:
    has_position_limits: true
    min_position: -2.268928
    max_position: 2.268928
    has_velocity_limits: true
    max_velocity: 1.5708
    has_acceleration_limits: true
    max_acceleration: 2.5
  joint_4:
    has_position_limits: true
    min_position: -2.96706
    max_position: 2.96706
    has_velocity_limits: true
    max_velocity: 3.1415
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_5:
    has_position_limits: true
    min_position: -2.094395
    max_position: 2.094395
    has_velocity_limits: true
    max_velocity: 3.1415
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_6:
    has_position_limits: true
    min_position: 0.0
    max_position: 6.283185
    has_velocity_limits: true
    max_velocity: 3.1415
    has_acceleration_limits: true
    max_acceleration: 5.0